# Generated by Django 2.1.15 on 2021-10-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingeredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingeredient',
            new_name='Ingredient',
        ),
    ]
